export const MESSAGE = {
  GET_GROUP_MESSAGE: 'message/getgroupmessage',
  GET_ONE_TO_ONE: 'message/getonetoone',
  GET_CONVERSATION: 'message/conversation',
  GET_MEMBERS: 'message/getmembersgroup',
  GET_RECALL: 'message/getrecallmessage',
  GET_FRIEND_SUGGEST: 'message/getlistfriendssuggest',
  SEND_MESSAGE: 'message/sendmessage',
  SEND_MESSAGE_ATTACH: 'message/sendmessageattach',
  REPLY_MESSAGE: 'message/replymessage',
  CREATE_GROUP: 'message/creategroup',
  ADD_MEMBERS_TO_GROUP: 'message/addmemberstogroup',
  DELETE_CONVERSATION: 'message/deleteconversation',
  RECALL_MESSAGE: 'message/recallmessage',
  SEND_REACT_MESSAGE: 'message/sendReactmessage',
  UPDATE_REACT_MESSAGE: 'message/updateReactmessage',
  SEARCH_MESSAGE: '/message/search',
  UPDATE_IMAGE_GROUP: 'message/changeimagegroup',
  UPDATE_GROUP_NAME: 'message/changegroupname',
  DELETE_REACT_MESSAGE: 'message/deleteReactmessage',
  LEAVE_OR_DELETE_MEMBER_GROUP: 'message/leaveanddeleteusergroup',
  CHANGE_ROLE_GROUP: 'message/changerolegroup',
  SEARCH_FR_AND_GR: 'message/searchfrandgr'
} as const
